version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: docker
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
