name: Debian

on:
  push:
    paths:
      - .github/workflows/debian.yml
      - shell/**
      - .dockerignore
      - .ssh.sh
      - debian.Dockerfile
  pull_request:
    paths:
      - .github/workflows/debian.yml
      - shell/**
      - .dockerignore
      - .ssh.sh
      - debian.Dockerfile

jobs:
  verify:
    runs-on: ubuntu-latest
    if: success() && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop'
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -f debian.Dockerfile -t kbuley/basedevcontainer .

  publish:
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          overrideConfig: |
            mode=Mainline

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: kbuley
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: kbuley+github
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set variables
        id: vars
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "platforms=linux/amd64,linux/arm64,linux/arm64/v8" >> $GITHUB_OUTPUT
          echo "os_version=debian" >> $GITHUB_OUTPUT

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          file: debian.Dockerfile
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.vars.outputs.created }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=v${{ steps.gitVersion.outputs.semVer }}
          tags: |
            kbuley/basedevcontainer:v${{ steps.gitVersion.outputs.semVer }}-${{ steps.vars.outputs.os_version }}
            quay.io/kbuley/basedevcontainer:v${{ steps.gitVersion.outputs.semVer }}-${{ steps.vars.outputs.os_version }}
          push: true

      - name: Tag release
        if: success() && (github.ref == 'refs/heads/main')
        run: |
          git tag "v${{ steps.gitVersion.outputs.semVer }}"
          git push --tags
