name: Ubuntu
on:
  push:
    paths:
      - .github/workflows/ubuntu.yml
      - shell/**
      - .dockerignore
      - .ssh.sh
      - ubuntu.Dockerfile
  pull_request:
    paths:
      - .github/workflows/ubuntu.yml
      - shell/**
      - .dockerignore
      - .ssh.sh
      - ubuntu.Dockerfile

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -f ubuntu.Dockerfile -t kbuley/basedevcontainer .

  publish:
    needs: [verify]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: kbuley
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set variables
        id: vars
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=commit::$(git rev-parse --short HEAD)
          echo ::set-output name=created::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo ::set-output name=version::$TAG
            echo ::set-output name=ubuntu_version::$TAG-ubuntu
            echo ::set-output name=platforms::linux/amd64,linux/arm64
          elif [ "$BRANCH" = "master" ]; then
            echo ::set-output name=version::latest
            echo ::set-output name=ubuntu_version::ubuntu
            echo ::set-output name=platforms::linux/amd64,linux/arm64
          else
            echo ::set-output name=version::$BRANCH
            echo ::set-output name=ubuntu_version::$BRANCH-ubuntu
            echo ::set-output name=platforms::linux/amd64,linux/arm64
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v5
        with:
          file: ubuntu.Dockerfile
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.vars.outputs.created }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
          tags: |
            kbuley/basedevcontainer:${{ steps.vars.outputs.ubuntu_version }}
          push: true
